[package]
name = "rustracer"
version = "0.1.0"
authors = ["ToruNiina <niina.toru.68u@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
rand_core = "0.4.0"
rand_os = "0.1.1"
rand_xoshiro = "0.1.0"
rand_xorshift = "0.1.1"
